version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/jovyan/
    ports:
      - "8888:8888"
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
volumes:
  pgdata: